#pragma once
#include "basehdr.h"

namespace inspectit {
	namespace utils {

		JAVA_INT JAVA_ABSTRACT = 0x400;
		JAVA_INT JAVA_FINAL = 0x10;
		JAVA_INT JAVA_INTERFACE = 0x200;
		JAVA_INT JAVA_NATIVE = 0x100;
		JAVA_INT JAVA_PRIVATE = 0x2;
		JAVA_INT JAVA_PROTECTED = 0x4;
		JAVA_INT JAVA_PUBLIC = 0x1;
		JAVA_INT JAVA_STATIC = 0x8;
		JAVA_INT JAVA_STRICT = 0x800;
		JAVA_INT JAVA_SYNCHRONIZED = 0x20;
		JAVA_INT JAVA_TRANSIENT = 0x80;
		JAVA_INT JAVA_VOLATILE = 0x40;

	}
}